# Generated by Django 3.2.4 on 2021-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Dr', 'Dr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss')], max_length=10)),
                ('first_name', models.CharField(blank=True, default='', max_length=60)),
                ('last_name', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
