# Generated by Django 3.2.4 on 2021-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Ms', 'Ms'), ('Mr', 'Mr')], max_length=10),
        ),
    ]
